#!/usr/bin/env python3
"""Constants and keyword tables for NyaNya messenger bridges."""

from __future__ import annotations

DEFAULT_MAX_MESSAGES = 24
DEFAULT_CODEX_TIMEOUT_SECONDS = 600
DEFAULT_CODEX_MAX_OUTPUT_CHARS = 6000
DEFAULT_TASK_QUEUE_MAX = 2
DEFAULT_PROTECTED_DELETE_PATHS = (
    ".env",
    ".env.sample",
    "src",
    "config",
    "prompts",
    "scripts",
    "pyproject.toml",
    "package.json",
)
CANCEL_COMMANDS = {"취소", "중지", "그만", "cancel", "/cancel", "stop", "/stop"}
CANCEL_ALL_COMMANDS = {"전체취소", "모두취소", "cancel_all", "/cancel_all", "stop_all", "/stop_all"}
CANCEL_USER_COMMANDS = {"사용자취소", "/사용자취소", "cancel_user", "/cancel_user", "stop_user", "/stop_user"}
SET_HOME_COMMANDS = {"set_home", "/set_home", "홈설정", "/홈설정"}
GET_HOME_COMMANDS = {"home", "/home", "get_home", "/get_home", "홈", "/홈"}
UNSET_HOME_COMMANDS = {"unset_home", "/unset_home", "홈해제", "/홈해제"}
HELP_COMMANDS = {"help", "/help", "commands", "/commands", "명령어", "/명령어", "도움말", "/도움말"}
TASK_STATUS_COMMANDS = {
    "tasks",
    "/tasks",
    "task",
    "/task",
    "queue",
    "/queue",
    "작업",
    "/작업",
    "작업목록",
    "/작업목록",
    "대기열",
    "/대기열",
    "진행상태",
    "/진행상태",
}
RESOURCE_KEYWORDS = (
    "resource",
    "resources",
    "process",
    "processes",
    "top",
    "cpu",
    "memory",
    "리소스",
    "프로세스",
    "메모리",
    "사용량",
    "많이 사용하는",
)
CODEX_AUTO_KEYWORDS = (
    "architecture",
    "bug",
    "code",
    "coding",
    "correlation",
    "csv",
    "data",
    "debug",
    "diff",
    "error",
    "excel",
    "fix",
    "implementation",
    "json",
    "log",
    "math",
    "mcp",
    "npm",
    "package",
    "plugin",
    "plugins",
    "python",
    "react",
    "reasoning",
    "report",
    "refactor",
    "regression",
    "script",
    "skill",
    "skills",
    "sql",
    "statistics",
    "test",
    "traceback",
    "typescript",
    "zip",
    "html",
    "보고서",
    "스킬",
    "요약",
    "정리",
    "첨부",
    "플러그인",
    "하네스",
    "검토",
    "계산",
    "구현",
    "그래프",
    "데이터",
    "디버그",
    "리팩터",
    "버그",
    "분석",
    "설계",
    "수정",
    "스크립트",
    "연산",
    "오류",
    "원인",
    "조사",
    "추론",
    "코딩",
    "코드",
    "통계",
    "테스트",
    "파일",
    "함수",
)
CODEX_AUTO_PHRASES = (
    "codex cli",
    "복잡한",
    "많이 사용하는 프로세스",
    "시스템 리소스",
    "작업 검수",
    "코드 리뷰",
)
FILE_TARGET_KEYWORDS = (
    "file",
    "files",
    "folder",
    "directory",
    "attachment",
    "workspace",
    "repo",
    "repository",
    "zip",
    "html",
    "report",
    "artifact",
    "압축",
    "첨부",
    "파일",
    "폴더",
    "디렉토리",
    "경로",
    "워크스페이스",
    "저장소",
    "프로젝트",
    "보고서",
    "자료",
)
FILE_MUTATION_KEYWORDS = (
    "add",
    "append",
    "change",
    "copy",
    "create",
    "delete",
    "edit",
    "make",
    "mkdir",
    "modify",
    "move",
    "patch",
    "remove",
    "rename",
    "replace",
    "save",
    "touch",
    "update",
    "write",
    "고쳐",
    "덮어",
    "만들",
    "바꿔",
    "복사",
    "삭제",
    "생성",
    "수정",
    "옮겨",
    "이동",
    "작성",
    "저장",
    "추가",
    "패치",
)
FILE_MUTATION_NEGATIONS = (
    "no changes",
    "no edit",
    "no modification",
    "read only",
    "read-only",
    "without changing",
    "without deleting",
    "without editing",
    "without modifying",
    "변경 없이",
    "삭제 없이",
    "생성 없이",
    "수정 없이",
    "쓰기 없이",
    "작성 없이",
    "저장 없이",
    "추가 없이",
    "편집 없이",
    "읽기 전용",
)
PROTECTED_DELETE_KEYWORDS = (
    "delete",
    "erase",
    "move",
    "remove",
    "rename",
    "rm",
    "rm -rf",
    "trash",
    "truncate",
    "unlink",
    "비워",
    "삭제",
    "없애",
    "옮겨",
    "이동",
    "이름 변경",
    "제거",
    "지워",
    "초기화",
)
FILE_READ_KEYWORDS = (
    "cat",
    "check",
    "find",
    "inspect",
    "list",
    "read",
    "review",
    "search",
    "show",
    "tree",
    "검토",
    "검색",
    "목록",
    "보여",
    "분석",
    "읽",
    "조사",
    "찾",
    "확인",
)
WEB_CHROME_KEYWORDS = (
    "browser",
    "chrome",
    "chromium",
    "devtools",
    "dom",
    "http://",
    "https://",
    "localhost",
    "page",
    "playwright",
    "selenium",
    "site",
    "url",
    "web",
    "website",
    "브라우저",
    "사이트",
    "스크린샷",
    "웹",
    "웹페이지",
    "페이지",
    "크롬",
)
BROWSER_OPERATION_KEYWORDS = (
    "click",
    "devtools",
    "inspect",
    "login",
    "open",
    "screenshot",
    "scroll",
    "test",
    "type",
    "verify",
    "visit",
    "클릭",
    "로그인",
    "브라우저에서",
    "스크린샷",
    "열어",
    "접속",
    "캡처",
    "크롬에서",
    "테스트",
    "확인",
)
CODEX_COMPLEXITY_KEYWORDS = (
    "api",
    "architecture",
    "build",
    "ci",
    "concurrency",
    "debug",
    "dependency",
    "integration",
    "mcp",
    "migration",
    "multi",
    "package",
    "parallel",
    "performance",
    "refactor",
    "regression",
    "statistics",
    "test",
    "traceback",
    "검증",
    "난이도",
    "대량",
    "동시",
    "디버그",
    "리팩터",
    "마이그레이션",
    "병렬",
    "복잡",
    "분석",
    "성능",
    "연동",
    "오류",
    "의존성",
    "전체",
    "테스트",
    "통계",
)
LOW_SIGNAL_CODEX_KEYWORDS = {
    "file",
    "files",
    "json",
    "log",
    "검토",
    "조사",
    "파일",
    "수정",
}
